# Generated by Django 4.2 on 2023-05-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('content', models.CharField(max_length=200)),
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POST', to='mytodos.users')),
            ],
        ),
    ]
